// SQL Studio tab: NL→SQL via local LLM, guardrail validation, execution,
// plain-English explanation, auto-repair, query saving. The draft (SQL + prompt)
// survives tab switches, and pinned fields from the Explorer are one drag away.
import {
  Hammer, MessageCircleQuestion, Play, Save, ShieldCheck, Sparkles, SquareTerminal,
  Trash2, Wand2,
} from 'lucide-react'
import { useEffect, useMemo, useRef, useState } from 'react'
import type { DragEvent } from 'react'
import { api } from '../api'
import { GuardrailPanel, ParamInputs, PinnedFields, ResultsTable, SchemaTree } from '../components/data'
import {
  Badge, Button, Card, EmptyState, Field, Input, Modal, Select, Textarea,
  useBusy, useConfirm, useToast,
} from '../components/ui'
import type { RunOutcome, ToolParam, Validation } from '../types'
import { dialectOf } from '../types'
import type { TabProps } from './shared'
import { detectParams, rememberConn, rememberedConn } from './shared'

export default function QueryStudio({ db, apply, goTo, pins, togglePin }: TabProps) {
  const [connId, setConnId] = useState(() => rememberedConn(db))
  const [sql, setSql] = useState(() => localStorage.getItem('doing.studio.sql') ?? '')
  const [nl, setNl] = useState(() => localStorage.getItem('doing.studio.nl') ?? '')
  const [paramValues, setParamValues] = useState<Record<string, string>>({})
  const [outcome, setOutcome] = useState<RunOutcome | null>(null)
  const [validation, setValidation] = useState<Validation | null>(null)
  const [explanation, setExplanation] = useState('')
  const [saveModal, setSaveModal] = useState(false)
  const [saveName, setSaveName] = useState('')
  const [saveDesc, setSaveDesc] = useState('')
  const editorRef = useRef<HTMLTextAreaElement>(null)
  const [busy, run] = useBusy()
  const toast = useToast()
  const confirm = useConfirm()

  // The work-in-progress query survives Explorer ↔ Studio round trips.
  useEffect(() => { localStorage.setItem('doing.studio.sql', sql) }, [sql])
  useEffect(() => { localStorage.setItem('doing.studio.nl', nl) }, [nl])

  const insertAtCursor = (text: string) => {
    const el = editorRef.current
    const pos = el ? el.selectionStart : sql.length
    const needsSpace = pos > 0 && !/[\s,(]$/.test(sql.slice(0, pos))
    const inserted = (needsSpace ? ' ' : '') + text
    setSql(sql.slice(0, pos) + inserted + sql.slice(pos))
    requestAnimationFrame(() => {
      el?.focus()
      el?.setSelectionRange(pos + inserted.length, pos + inserted.length)
    })
  }

  const conn = db.connections.find((c) => c.id === connId) ?? db.connections[0]
  const catalog = conn ? db.catalog[conn.id] : undefined
  const queries = useMemo(() => db.queries.filter((q) => !conn || q.connection_id === conn.id), [db.queries, conn])

  const params: ToolParam[] = useMemo(
    () => detectParams(sql).map((name) => ({ name, type: 'string', description: '', required: true, default: null })),
    [sql],
  )

  if (db.connections.length === 0) {
    return (
      <EmptyState
        icon={SquareTerminal}
        title="The studio needs a connection"
        desc="Create a connection (or the demo sandbox) to start composing queries."
        action={<Button variant="outline" onClick={() => goTo('connections')}>Go to connections</Button>}
      />
    )
  }

  const bindParams = (): Record<string, unknown> => {
    const bound: Record<string, unknown> = {}
    for (const p of params) bound[p.name] = paramValues[p.name] ?? ''
    return bound
  }

  const generate = () => conn && run('generate', async () => {
    const { result } = await api.generateSql(conn.id, nl)
    setSql(result.sql)
    setValidation(result.validation ?? null)
    setExplanation(result.explanation)
    setOutcome(null)
    toast.push('SQL generated by the LLM — review, validate, run.', 'success')
  })

  const execute = () => conn && run('run', async () => {
    const env = await api.runSql(conn.id, sql, bindParams())
    apply(env)
    setOutcome(env.result)
    setValidation(env.result.validation ?? null)
    if (!env.result.ok) toast.push('The query failed — “Fix with AI” can suggest a correction.', 'warn')
  })

  const validate = () => conn && run('validate', async () => {
    const { result } = await api.validateSql(conn.id, sql)
    setValidation(result)
  })

  const explain = () => conn && run('explain', async () => {
    const { result } = await api.explainSql(sql, dialectOf(conn.kind))
    setExplanation(result.explanation)
  })

  const fix = () => conn && outcome && !outcome.ok && run('fix', async () => {
    const { result } = await api.fixSql(conn.id, sql, outcome.error ?? '')
    setSql(result.sql)
    setValidation(result.validation ?? null)
    setExplanation(result.explanation)
    setOutcome(null)
    toast.push('LLM-suggested fix applied in the editor.', 'success')
  })

  const save = () => conn && run('save', async () => {
    const env = await api.createQuery({
      name: saveName || 'Untitled query', description: saveDesc,
      connection_id: conn.id, sql,
    })
    apply(env)
    setSaveModal(false)
    setSaveName('')
    setSaveDesc('')
    toast.push('Query saved — turn it into an MCP tool in the Tools tab.', 'success')
  })

  const onDrop = (e: DragEvent<HTMLTextAreaElement>) => {
    const text = e.dataTransfer.getData('text/plain')
    if (!text) return
    e.preventDefault()
    const el = editorRef.current
    const pos = el ? el.selectionStart : sql.length
    setSql(sql.slice(0, pos) + text + sql.slice(pos))
  }

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 className="text-lg font-semibold">SQL Studio</h2>
          <p className="text-xs text-zinc-500">
            Describe your need in plain English, the local LLM writes the SQL. Drag & drop tables into the editor.
          </p>
        </div>
        <Select value={conn?.id ?? ''} onChange={(e) => { setConnId(e.target.value); rememberConn(e.target.value) }} className="w-56">
          {db.connections.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}
        </Select>
      </div>

      <PinnedFields pins={pins} onTogglePin={togglePin} onInsert={insertAtCursor} />

      <div className="grid grid-cols-1 gap-4 xl:grid-cols-4">
        <div className="space-y-4 xl:col-span-1">
          <Card
            title="Schema"
            subtitle="Drag tables or fields into the editor — ★ to pin"
            actions={
              <Button size="sm" variant="ghost" onClick={() => goTo('catalog')}
                title="Check the data in the Explorer — your query draft is kept">
                Explorer →
              </Button>
            }
          >
            <SchemaTree catalog={catalog} draggable pins={pins} onTogglePin={togglePin} />
          </Card>
          <Card title={`Saved queries (${queries.length})`}>
            {queries.length === 0 ? (
              <p className="text-xs text-zinc-400">No query for this connection.</p>
            ) : (
              <div className="max-h-64 space-y-1 overflow-y-auto">
                {queries.map((q) => (
                  <div key={q.id} className="group flex items-center gap-2 rounded-md px-2 py-1.5 text-xs hover:bg-zinc-100 dark:hover:bg-zinc-800">
                    <button className="flex-1 truncate text-left font-medium" onClick={() => { setSql(q.sql); setOutcome(null); setValidation(null) }}>
                      {q.name}
                      {q.last_run && (
                        <span className={q.last_run.ok ? 'ml-1.5 text-emerald-500' : 'ml-1.5 text-red-500'}>
                          {q.last_run.ok ? `✓ ${q.last_run.rows}r` : '✗'}
                        </span>
                      )}
                    </button>
                    <button
                      className="hidden text-red-400 group-hover:block"
                      onClick={() => {
                        void confirm({ title: 'Delete query', message: `Delete “${q.name}”?` })
                          .then((ok) => { if (ok) run(`delq-${q.id}`, async () => apply(await api.deleteQuery(q.id))) })
                      }}
                    >
                      <Trash2 size={12} />
                    </button>
                  </div>
                ))}
              </div>
            )}
          </Card>
        </div>

        <div className="space-y-4 xl:col-span-3">
          <Card title="AI assistant" subtitle="Natural language → parameterized SQL">
            <div className="flex gap-2">
              <Input
                value={nl}
                onChange={(e) => setNl(e.target.value)}
                onKeyDown={(e) => { if (e.key === 'Enter' && nl.trim()) generate() }}
                placeholder="e.g. top 10 customers by revenue for a given country"
              />
              <Button icon={Sparkles} busy={busy === 'generate'} onClick={generate} disabled={!nl.trim()}>
                Generate
              </Button>
            </div>
          </Card>

          <Card
            title="SQL editor"
            subtitle={conn ? `Dialect: ${dialectOf(conn.kind)}` : undefined}
            actions={
              <div className="flex gap-1.5">
                <Button size="sm" variant="outline" icon={ShieldCheck} busy={busy === 'validate'} onClick={validate} disabled={!sql.trim()}>Validate</Button>
                <Button size="sm" variant="outline" icon={MessageCircleQuestion} busy={busy === 'explain'} onClick={explain} disabled={!sql.trim()}>Explain</Button>
                <Button size="sm" icon={Play} busy={busy === 'run'} onClick={execute} disabled={!sql.trim()} title="⌘/Ctrl + Enter">Run</Button>
              </div>
            }
          >
            <Textarea
              ref={editorRef}
              value={sql}
              onChange={(e) => setSql(e.target.value)}
              onDrop={onDrop}
              onDragOver={(e) => e.preventDefault()}
              onKeyDown={(e) => {
                if ((e.metaKey || e.ctrlKey) && e.key === 'Enter' && sql.trim()) {
                  e.preventDefault()
                  execute()
                }
              }}
              rows={9}
              spellCheck={false}
              placeholder={'SELECT country, COUNT(*) AS clients\nFROM customers\nWHERE segment = :segment\nGROUP BY country\nORDER BY clients DESC'}
              className="font-mono text-xs leading-relaxed"
            />
            {params.length > 0 && (
              <div className="mt-3">
                <p className="mb-1.5 text-xs font-medium uppercase tracking-wide text-zinc-400">
                  Detected parameters <Badge tone="brand">{params.length}</Badge>
                </p>
                <ParamInputs params={params} values={paramValues} onChange={(name, value) => setParamValues((v) => ({ ...v, [name]: value }))} />
              </div>
            )}
            <div className="mt-3 space-y-2">
              <GuardrailPanel validation={validation} />
              {explanation && (
                <div className="rounded-lg bg-sky-50 p-3 text-xs leading-relaxed text-sky-800 dark:bg-sky-950/40 dark:text-sky-200">
                  <span className="font-semibold">LLM explanation: </span>{explanation}
                </div>
              )}
            </div>
            <div className="mt-3 flex items-center justify-between">
              <div className="flex gap-2">
                {outcome && !outcome.ok && (
                  <Button size="sm" variant="outline" icon={Wand2} busy={busy === 'fix'} onClick={fix}>
                    Fix with AI
                  </Button>
                )}
              </div>
              <div className="flex gap-2">
                <Button size="sm" variant="outline" icon={Save} onClick={() => setSaveModal(true)} disabled={!sql.trim()}>
                  Save
                </Button>
                <Button size="sm" variant="outline" icon={Hammer} onClick={() => goTo('tools')} disabled={!sql.trim()}>
                  Make it a tool →
                </Button>
              </div>
            </div>
          </Card>

          {outcome && (
            <Card title="Results">
              <ResultsTable outcome={outcome} />
            </Card>
          )}
        </div>
      </div>

      <Modal
        open={saveModal}
        onClose={() => setSaveModal(false)}
        title="Save query"
        footer={
          <>
            <Button variant="outline" onClick={() => setSaveModal(false)}>Cancel</Button>
            <Button busy={busy === 'save'} onClick={save}>Save</Button>
          </>
        }
      >
        <div className="space-y-3">
          <Field label="Name">
            <Input value={saveName} onChange={(e) => setSaveName(e.target.value)} placeholder="Top customers by revenue" />
          </Field>
          <Field label="Description (optional)">
            <Textarea value={saveDesc} onChange={(e) => setSaveDesc(e.target.value)} rows={2} />
          </Field>
        </div>
      </Modal>
    </div>
  )
}
